### ISSUE TITLE
codon_table.txt

### ISSUE THREAD

**Issue by RobertoRun** [tsackton/linked-selection#1]
Would you like to share the codon_table.txt file for identifying the 4D sites?

**Comment by tsackton** [comment]
Codon_table.txt is just the codon table for codons with 4d sites. You can
get it anywhere. See comments in code for details. The file we used in our analysis is now added to the misc_scripts folder, named codon_table.txt.

Note this code is provided as is with no guarantee of functionality.
Generally speaking it seems to work okay with NCBI data but reportedly
often fails on other fasta / gff files.

**Comment by RobertoRun** [comment]
Thank you so much!

In the codon_table.txt, there is a duplicated line.

For the script, i don't output the 4d site of last sequence in the genome file!
